Remove unnecessary static assertion
This assertion is not required. The docs for std::mem::transmute read:

    Both types must have the same size. Compilation will fail if this is
    not guaranteed.

I have confirmed this to be the case by trying to transmute two
different variables of different length:

    error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
      --> src/sys/socket/addr.rs:44:14
       |
    44 |     unsafe { mem::transmute("asdfasd") }
       |              ^^^^^^^^^^^^^^
       |
       = note: source type: `&str` (128 bits)
       = note: target type: `in_addr` (32 bits)

Given that this is the only usage of the `static_assertions` crates,
this allows dropping an unnecessary dependency.