Merge #2033
2033: remove unused mut from two variable declarations in sys/socket/mod.rs r=asomers a=inglorion

This addresses diagnostics like:

  error: variable does not need to be mutable
      --> src/sys/socket/mod.rs:1537:13
       |
  1537 |         let mut p = &mut mmsghdr.msg_hdr;

Co-authored-by: Bob Haarman <inglorion@google.com>